apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd1
spec:
  project: default

  source:
    repoURL: https://github.com/mandarpalsodkar/webfrontend.git
    targetRevision: HEAD
    path: samples/nodejs/getting-started/webfrontend/webfrontend/
  destination: 
    server: https://kubernetes.default.svc
    

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true